cars= ["BMW", "Lambo", "Audi","Jeep"]
print(cars)
print(cars[2])
print(type(cars))
print(len(str(cars)))
print(len(cars))
print(cars[:2])
print(cars[::-1])
print(cars[2:6])
print(cars[-1:-3])
print(cars[1:])
